<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <MiniExcelRustPackageVersion Condition="'$(MiniExcelRustPackageVersion)' == ''">0.1.0-preview.2</MiniExcelRustPackageVersion>
    <MiniExcelVersion>2.0.0-preview.4</MiniExcelVersion>
    <RestoreAdditionalProjectSources>https://api.nuget.org/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="$(MiniExcelVersion)" Condition="'$(MiniExcelSourceRoot)' == ''" />
    <PackageReference Include="MiniExcelRust" Version="$(MiniExcelRustPackageVersion)" />
    <ProjectReference Include="$(MiniExcelSourceRoot)\src\MiniExcel\MiniExcel.csproj" Condition="'$(MiniExcelSourceRoot)' != ''" />
  </ItemGroup>

</Project>
